app = "zus-pension-simulator"
primary_region = "fra"

[build]

[env]
  PORT = "8000"
  ZUS_CSV_PATH = "data/processed/zus_forecast_all.csv"
  BASE_AVG_WAGE_TODAY = "8000"
  SUPABASE_URL = "https://ehddhxqzeqvxrhblpzag.supabase.co"
  SUPABASE_KEY = "sb_secret_Qv84H7GycMBMWz-iTITFRA_Z_o11PYh"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "echo 'Deploying ZUS Pension Simulator'"
